// @ts-nocheck
export {ReactComponent as AlbertPark} from './albert_park.svg';
export {ReactComponent as Americas} from './americas.svg';
export {ReactComponent as Bahrain} from './bahrain.svg';
export {ReactComponent as Baku} from './baku.svg';
export {ReactComponent as Catalunya} from './catalunya.svg';
export {ReactComponent as Estoril} from './estoril.svg';
export {ReactComponent as Hungaroring} from './hungaroring.svg';
export {ReactComponent as Imola} from './imola.svg';
export {ReactComponent as Interlagos} from './interlagos.svg';
export {ReactComponent as Jeddah} from './jeddah.svg';
export {ReactComponent as Losail} from './losail.svg';
export {ReactComponent as MarinaBay} from './marina_bay.svg';
export {ReactComponent as Miami} from './miami.svg';
export {ReactComponent as Monaco} from './monaco.svg';
export {ReactComponent as Monza} from './monza.svg';
export {ReactComponent as RedBullRing} from './red_bull_ring.svg';
export {ReactComponent as Ricard} from './ricard.svg';
export {ReactComponent as Rodriguez} from './rodriguez.svg';
export {ReactComponent as Shanghai} from './shanghai.svg';
export {ReactComponent as Silverstone} from './silverstone.svg';
export {ReactComponent as Sochi} from './sochi.svg';
export {ReactComponent as Spa} from './spa.svg';
export {ReactComponent as Suzuka} from './suzuka.svg';
// export {ReactComponent as Vegas} from './vegas.svg';
export {ReactComponent as Villeneuve} from './villeneuve.svg';
export {ReactComponent as YasMarina} from './yas_marina.svg';
export {ReactComponent as Zandvoort} from './zandvoort.svg';

// export {ReactComponent as Adelaide} from './adelaide.svg';
// export {ReactComponent as Aindiab} from './ain-diab.svg';
// export {ReactComponent as Aintree} from './aintree.svg';
// export {ReactComponent as Anderstorp} from './anderstorp.svg';
// export {ReactComponent as Avus} from './avus.svg';
// export {ReactComponent as Boavista} from './boavista.svg';
// export {ReactComponent as Brands_hatch} from './brands_hatch.svg';
// export {ReactComponent as Bremgarten} from './bremgarten.svg';
// export {ReactComponent as Buddh} from './buddh.svg';
// export {ReactComponent as Charade} from './charade.svg';
// export {ReactComponent as Dallas} from './dallas.svg';
// export {ReactComponent as Detroit} from './detroit.svg';
// export {ReactComponent as Dijon} from './dijon.svg';
// export {ReactComponent as Donington} from './donington.svg';
// export {ReactComponent as Essarts} from './essarts.svg';
// export {ReactComponent as Fuji} from './fuji.svg';
// export {ReactComponent as Galvez} from './galvez.svg';
// export {ReactComponent as George} from './george.svg';
// export {ReactComponent as Hockenheimring} from './hockenheimring.svg';
// export {ReactComponent as Indianapolis} from './indianapolis.svg';
// export {ReactComponent as Istanbul} from './istanbul.svg';
// export {ReactComponent as Jacarepagua} from './jacarepagua.svg';
// export {ReactComponent as Jarama} from './jarama.svg';
// export {ReactComponent as Jerez} from './jerez.svg';
// export {ReactComponent as Kyalami} from './kyalami.svg';
// export {ReactComponent as Las_vegas} from './las_vegas.svg';
// export {ReactComponent as Lemans} from './lemans.svg';
// export {ReactComponent as Long_beach} from './long_beach.svg';
// export {ReactComponent as Magny_cours} from './magny_cours.svg';
// export {ReactComponent as Monsanto} from './monsanto.svg';
// export {ReactComponent as Montjuic} from './montjuic.svg';
// export {ReactComponent as Mosport} from './mosport.svg';
// export {ReactComponent as Mugello} from './mugello.svg';
// export {ReactComponent as Nivelles} from './nivelles.svg';
// export {ReactComponent as Nurburgring} from './nurburgring.svg';
// export {ReactComponent as Okayama} from './okayama.svg';
// export {ReactComponent as Pedralbes} from './pedralbes.svg';
// export {ReactComponent as Pescara} from './pescara.svg';
// export {ReactComponent as Phoenix} from './phoenix.svg';
// export {ReactComponent as Portimao} from './portimao.svg';
// export {ReactComponent as Reims} from './reims.svg';
// export {ReactComponent as Riverside} from './riverside.svg';
// export {ReactComponent as Sebring} from './sebring.svg';
// export {ReactComponent as Sepang} from './sepang.svg';
// export {ReactComponent as Tremblant} from './tremblant.svg';
// export {ReactComponent as Valencia} from './valencia.svg';
// export {ReactComponent as Watkins_glen} from './watkins_glen.svg';
// export {ReactComponent as Yeongam} from './yeongam.svg';
// export {ReactComponent as Zeltweg} from './zeltweg.svg';
// export {ReactComponent as Zolder} from './zolder.svg';