// @ts-nocheck
export {default as AlbertPark} from './albert_park.svg';
export {default as Americas} from './americas.svg';
export {default as Bahrain} from './bahrain.svg';
export {default as Baku} from './baku.svg';
export {default as Catalunya} from './catalunya.svg';
export {default as Estoril} from './estoril.svg';
export {default as Hungaroring} from './hungaroring.svg';
export {default as Imola} from './imola.svg';
export {default as Interlagos} from './interlagos.svg';
export {default as Jeddah} from './jeddah.svg';
export {default as Losail} from './losail.svg';
export {default as MarinaBay} from './marina_bay.svg';
export {default as Miami} from './miami.svg';
export {default as Monaco} from './monaco.svg';
export {default as Monza} from './monza.svg';
export {default as RedBullRing} from './red_bull_ring.svg';
export {default as Ricard} from './ricard.svg';
export {default as Rodriguez} from './rodriguez.svg';
export {default as Shanghai} from './shanghai.svg';
export {default as Silverstone} from './silverstone.svg';
export {default as Sochi} from './sochi.svg';
export {default as Spa} from './spa.svg';
export {default as Suzuka} from './suzuka.svg';
// export {default as Vegas} from './vegas.svg';
export {default as Villeneuve} from './villeneuve.svg';
export {default as YasMarina} from './yas_marina.svg';
export {default as Zandvoort} from './zandvoort.svg';

// export {default as Adelaide} from './adelaide.svg';
// export {default as Aindiab} from './ain-diab.svg';
// export {default as Aintree} from './aintree.svg';
// export {default as Anderstorp} from './anderstorp.svg';
// export {default as Avus} from './avus.svg';
// export {default as Boavista} from './boavista.svg';
// export {default as Brands_hatch} from './brands_hatch.svg';
// export {default as Bremgarten} from './bremgarten.svg';
// export {default as Buddh} from './buddh.svg';
// export {default as Charade} from './charade.svg';
// export {default as Dallas} from './dallas.svg';
// export {default as Detroit} from './detroit.svg';
// export {default as Dijon} from './dijon.svg';
// export {default as Donington} from './donington.svg';
// export {default as Essarts} from './essarts.svg';
// export {default as Fuji} from './fuji.svg';
// export {default as Galvez} from './galvez.svg';
// export {default as George} from './george.svg';
// export {default as Hockenheimring} from './hockenheimring.svg';
// export {default as Indianapolis} from './indianapolis.svg';
// export {default as Istanbul} from './istanbul.svg';
// export {default as Jacarepagua} from './jacarepagua.svg';
// export {default as Jarama} from './jarama.svg';
// export {default as Jerez} from './jerez.svg';
// export {default as Kyalami} from './kyalami.svg';
// export {default as Las_vegas} from './las_vegas.svg';
// export {default as Lemans} from './lemans.svg';
// export {default as Long_beach} from './long_beach.svg';
// export {default as Magny_cours} from './magny_cours.svg';
// export {default as Monsanto} from './monsanto.svg';
// export {default as Montjuic} from './montjuic.svg';
// export {default as Mosport} from './mosport.svg';
// export {default as Mugello} from './mugello.svg';
// export {default as Nivelles} from './nivelles.svg';
// export {default as Nurburgring} from './nurburgring.svg';
// export {default as Okayama} from './okayama.svg';
// export {default as Pedralbes} from './pedralbes.svg';
// export {default as Pescara} from './pescara.svg';
// export {default as Phoenix} from './phoenix.svg';
// export {default as Portimao} from './portimao.svg';
// export {default as Reims} from './reims.svg';
// export {default as Riverside} from './riverside.svg';
// export {default as Sebring} from './sebring.svg';
// export {default as Sepang} from './sepang.svg';
// export {default as Tremblant} from './tremblant.svg';
// export {default as Valencia} from './valencia.svg';
// export {default as Watkins_glen} from './watkins_glen.svg';
// export {default as Yeongam} from './yeongam.svg';
// export {default as Zeltweg} from './zeltweg.svg';
// export {default as Zolder} from './zolder.svg';